/**
 * @file Automatically generated by barrelsby.
 */

export * from "./block.test";
export * from "./build-in-functions.test";
export * from "./class.test";
export * from "./for-loop.test";
export * from "./global.test";
export * from "./if.test";
export * from "./import.test";
export * from "./lambda-functions.test";
export * from "./math.test";
export * from "./module.test";
export * from "./self-eval.test";
export * from "./switch.test";
export * from "./syntax-sugar.test";
export * from "./terminator.test";
export * from "./user-defined-functions.test";
export * from "./variables.test";
export * from "./while.test";
